# MindSense AI - Data Preprocessing

## Objective
Prepare the raw dataset for machine learning by:

- Removing unnecessary features
- Handling structural missing values
- Encoding categorical variables
- Preparing the final clean dataset

Prepared By: Musharraf Bubere

Date: 18 July 2026

Version: 1.0

## Engineering Decisions Applied

- ED-04: Remove Identifier Feature (Name)
- ED-05: Preserve Structural Missing Values
- ED-06: Retain Population Feature
- ED-07: Feature-Specific Encoding Strategy
- ED-08: Binary Encoding for Binary Features
- ED-09: Ordinal Encoding for Ordered Features
- ED-10: Analyze High-Cardinality Features
- ED-11: One-Hot Encoding for Nominal Features

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_raw = pd.read_csv("../Dataset/Raw/MindSense_AI_Selected_Dataset_v1.csv")
df = df_raw.copy()

In [3]:
df.head()

,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Pooja,Female,37,Ghaziabad,Working Professional,Teacher,NaN,2.0,NaN,NaN,4.0,7-8 hours,Moderate,MA,No,6,2,No,No
1,Reyansh,Male,60,Kalyan,Working Professional,Financial Analyst,NaN,4.0,NaN,NaN,3.0,5-6 hours,Unhealthy,B.Com,Yes,0,4,Yes,No
2,Manvi,Female,42,Bhopal,Working Professional,Teacher,NaN,2.0,NaN,NaN,3.0,5-6 hours,Moderate,M.Com,No,0,2,No,No
3,Isha,Female,44,Thane,Working Professional,Teacher,NaN,3.0,NaN,NaN,5.0,7-8 hours,Healthy,MD,Yes,1,2,Yes,No
4,Aarav,Male,48,Indore,Working Professional,UX/UI Designer,NaN,4.0,NaN,NaN,3.0,7-8 hours,Moderate,BE,Yes,6,5,Yes,No

In [4]:
print("Sleep Duration:")
print(df["Sleep Duration"].unique())

print("\nDietary Habits:")
print(df["Dietary Habits"].unique())

print("\nWorking Professional or Student:")
print(df["Working Professional or Student"].unique())

print("\nGender:")
print(df["Gender"].unique())

print("\nHave you ever had suicidal thoughts?:")
print(df["Have you ever had suicidal thoughts ?"].unique())

print("\nFamily History of Mental Illness:")
print(df["Family History of Mental Illness"].unique())

Sleep Duration:
<StringArray>
['7-8 hours', '5-6 hours', 'More than 8 hours', 'Less than 5 hours']
Length: 4, dtype: str

Dietary Habits:
<StringArray>
['Moderate', 'Unhealthy', 'Healthy']
Length: 3, dtype: str

Working Professional or Student:
<StringArray>
['Working Professional', 'Student']
Length: 2, dtype: str

Gender:
<StringArray>
['Female', 'Male']
Length: 2, dtype: str

Have you ever had suicidal thoughts?:
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Family History of Mental Illness:
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [5]:
df.drop(columns=["Name"], inplace=True)

In [6]:
print(df.shape)
df.head()

(2556, 18)

,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,Female,37,Ghaziabad,Working Professional,Teacher,NaN,2.0,NaN,NaN,4.0,7-8 hours,Moderate,MA,No,6,2,No,No
1,Male,60,Kalyan,Working Professional,Financial Analyst,NaN,4.0,NaN,NaN,3.0,5-6 hours,Unhealthy,B.Com,Yes,0,4,Yes,No
2,Female,42,Bhopal,Working Professional,Teacher,NaN,2.0,NaN,NaN,3.0,5-6 hours,Moderate,M.Com,No,0,2,No,No
3,Female,44,Thane,Working Professional,Teacher,NaN,3.0,NaN,NaN,5.0,7-8 hours,Healthy,MD,Yes,1,2,Yes,No
4,Male,48,Indore,Working Professional,UX/UI Designer,NaN,4.0,NaN,NaN,3.0,7-8 hours,Moderate,BE,Yes,6,5,Yes,No

In [7]:
gender_mapping = {
    "Female": 0,
    "Male": 1
}

df["Gender"] = df["Gender"].map(gender_mapping)

In [8]:
print(df["Gender"].unique())

[0 1]

In [9]:
df[["Gender"]].head()

   Gender
0       0
1       1
2       0
3       0
4       1

In [10]:
print(df["Gender"].dtype)

int64

In [11]:
working_professional_mapping = {
    "Student": 0,
    "Working Professional": 1
}

df["Working Professional or Student"] = df["Working Professional or Student"].map(
    working_professional_mapping
)

In [12]:
print(df["Working Professional or Student"].unique())
print(df["Working Professional or Student"].dtype)

[1 0]
int64

In [13]:
suicidal_thoughts_mapping = {
    "No": 0,
    "Yes": 1
}

df["Have you ever had suicidal thoughts ?"] = df["Have you ever had suicidal thoughts ?"].map(
    suicidal_thoughts_mapping
)

In [14]:
print(df["Have you ever had suicidal thoughts ?"].unique())
print(df["Have you ever had suicidal thoughts ?"].dtype)

[0 1]
int64

In [15]:
family_history_mapping = {
    "No": 0,
    "Yes": 1
}

df["Family History of Mental Illness"] = df["Family History of Mental Illness"].map(
    family_history_mapping
)

In [16]:
print(df["Family History of Mental Illness"].unique())
print(df["Family History of Mental Illness"].dtype)

[0 1]
int64

In [17]:
df.head()

,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,37,Ghaziabad,1,Teacher,NaN,2.0,NaN,NaN,4.0,7-8 hours,Moderate,MA,0,6,2,0,No
1,1,60,Kalyan,1,Financial Analyst,NaN,4.0,NaN,NaN,3.0,5-6 hours,Unhealthy,B.Com,1,0,4,1,No
2,0,42,Bhopal,1,Teacher,NaN,2.0,NaN,NaN,3.0,5-6 hours,Moderate,M.Com,0,0,2,0,No
3,0,44,Thane,1,Teacher,NaN,3.0,NaN,NaN,5.0,7-8 hours,Healthy,MD,1,1,2,1,No
4,1,48,Indore,1,UX/UI Designer,NaN,4.0,NaN,NaN,3.0,7-8 hours,Moderate,BE,1,6,5,1,No

In [18]:
sleep_duration_mapping = {
    "Less than 5 hours": 0,
    "5-6 hours": 1,
    "7-8 hours": 2,
    "More than 8 hours": 3
}

df["Sleep Duration"] = df["Sleep Duration"].map(sleep_duration_mapping)

In [19]:
print(df["Sleep Duration"].unique())
print(df["Sleep Duration"].dtype)

[2 1 3 0]
int64

In [20]:
df[["Sleep Duration"]].head()

   Sleep Duration
0               2
1               1
2               1
3               2
4               2

In [21]:
dietary_habits_mapping = {
    "Unhealthy": 0,
    "Moderate": 1,
    "Healthy": 2
}

df["Dietary Habits"] = df["Dietary Habits"].map(dietary_habits_mapping)

In [22]:
print(df["Dietary Habits"].unique())
print(df["Dietary Habits"].dtype)
df[["Dietary Habits"]].head()

[1 0 2]
int64

   Dietary Habits
0               1
1               0
2               1
3               2
4               1

In [23]:
city_encoded = pd.get_dummies(
    df["City"],
    prefix="City",
    dtype=int
)

In [24]:
city_encoded.head()

,City_Agra,City_Ahmedabad,City_Bangalore,City_Bhopal,City_Chennai,City_Delhi,City_Faridabad,City_Ghaziabad,City_Hyderabad,City_Indore,...,City_Patna,City_Pune,City_Rajkot,City_Srinagar,City_Surat,City_Thane,City_Vadodara,City_Varanasi,City_Vasai-Virar,City_Visakhapatnam
0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [25]:
city_encoded.info()

<class 'pandas.DataFrame'>
RangeIndex: 2556 entries, 0 to 2555
Data columns (total 30 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   City_Agra           2556 non-null   int64
 1   City_Ahmedabad      2556 non-null   int64
 2   City_Bangalore      2556 non-null   int64
 3   City_Bhopal         2556 non-null   int64
 4   City_Chennai        2556 non-null   int64
 5   City_Delhi          2556 non-null   int64
 6   City_Faridabad      2556 non-null   int64
 7   City_Ghaziabad      2556 non-null   int64
 8   City_Hyderabad      2556 non-null   int64
 9   City_Indore         2556 non-null   int64
 10  City_Jaipur         2556 non-null   int64
 11  City_Kalyan         2556 non-null   int64
 12  City_Kanpur         2556 non-null   int64
 13  City_Kolkata        2556 non-null   int64
 14  City_Lucknow        2556 non-null   int64
 15  City_Ludhiana       2556 non-null   int64
 16  City_Meerut         2556 non-null   int64
 17  City_Mumbai         2556 non-null   int64
 18  City_Nagpur         2556 non-null   int64
 19  City_Nashik         2556 non-null   int64
 20  City_Patna          2556 non-null   int64
 21  City_Pune           2556 non-null   int64
 22  City_Rajkot         2556 non-null   int64
 23  City_Srinagar       2556 non-null   int64
 24  City_Surat          2556 non-null   int64
 25  City_Thane          2556 non-null   int64
 26  City_Vadodara       2556 non-null   int64
 27  City_Varanasi       2556 non-null   int64
 28  City_Vasai-Virar    2556 non-null   int64
 29  City_Visakhapatnam  2556 non-null   int64
dtypes: int64(30)
memory usage: 599.2 KB

In [26]:
df = pd.concat([df, city_encoded], axis=1)

In [27]:
df.drop(columns=["City"], inplace=True)

In [28]:
print(df["Profession"].nunique())
print(df["Profession"].unique())
print(df["Profession"].isnull().sum())

35
<StringArray>
[               'Teacher',      'Financial Analyst',         'UX/UI Designer',
         'Civil Engineer',             'Accountant',                 'Lawyer',
         'Content Writer',                      nan,                  'Pilot',
       'Customer Support',                  'Judge',              'Architect',
             'HR Manager',       'Digital Marketer',        'Sales Executive',
       'Business Analyst',    'Mechanical Engineer',             'Consultant',
         'Data Scientist',             'Pharmacist',      'Software Engineer',
      'Travel Consultant',                'Manager',           'Entrepreneur',
                 'Doctor',             'Researcher',                'Plumber',
    'Finanancial Analyst',      'Marketing Manager', 'Educational Consultant',
                'Chemist',       'Research Analyst',                   'Chef',
            'Electrician',       'Graphic Designer',      'Investment Banker']
Length: 36, dtype: str
673

In [29]:
df["Profession"] = df["Profession"].replace(
    "Finanancial Analyst",
    "Financial Analyst"
)

In [30]:
df["Profession"].nunique()

34

In [31]:
pd.crosstab(
    df["Working Professional or Student"],
    df["Profession"].isnull()
)

Profession                       False  True
Working Professional or Student
0                                    0    502
1                                 1883    171

In [32]:
df.loc[
    (df["Working Professional or Student"] == 0) &
    (df["Profession"].isnull()),
    "Profession"
] = "Student"

In [33]:
df.loc[
    (df["Working Professional or Student"] == 1) &
    (df["Profession"].isnull()),
    "Profession"
] = "Unknown"

In [34]:
df["Profession"].isnull().sum()

np.int64(0)

In [35]:
profession_encoded = pd.get_dummies(
    df["Profession"],
    prefix="Profession",
    dtype=int
)

In [36]:
df = pd.concat([df, profession_encoded], axis=1)

In [37]:
df.drop(columns=["Profession"], inplace=True)

In [38]:
profession_encoded.info()

<class 'pandas.DataFrame'>
RangeIndex: 2556 entries, 0 to 2555
Data columns (total 36 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Profession_Accountant              2556 non-null   int64
 1   Profession_Architect               2556 non-null   int64
 2   Profession_Business Analyst        2556 non-null   int64
 3   Profession_Chef                    2556 non-null   int64
 4   Profession_Chemist                 2556 non-null   int64
 5   Profession_Civil Engineer          2556 non-null   int64
 6   Profession_Consultant              2556 non-null   int64
 7   Profession_Content Writer          2556 non-null   int64
 8   Profession_Customer Support        2556 non-null   int64
 9   Profession_Data Scientist          2556 non-null   int64
 10  Profession_Digital Marketer        2556 non-null   int64
 11  Profession_Doctor                  2556 non-null   int64
 12  Profession_Educational Consultant  2556 non-null   int64
 13  Profession_Electrician             2556 non-null   int64
 14  Profession_Entrepreneur            2556 non-null   int64
 15  Profession_Financial Analyst       2556 non-null   int64
 16  Profession_Graphic Designer        2556 non-null   int64
 17  Profession_HR Manager              2556 non-null   int64
 18  Profession_Investment Banker       2556 non-null   int64
 19  Profession_Judge                   2556 non-null   int64
 20  Profession_Lawyer                  2556 non-null   int64
 21  Profession_Manager                 2556 non-null   int64
 22  Profession_Marketing Manager       2556 non-null   int64
 23  Profession_Mechanical Engineer     2556 non-null   int64
 24  Profession_Pharmacist              2556 non-null   int64
 25  Profession_Pilot                   2556 non-null   int64
 26  Profession_Plumber                 2556 non-null   int64
 27  Profession_Research Analyst        2556 non-null   int64
 28  Profession_Researcher              2556 non-null   int64
 29  Profession_Sales Executive         2556 non-null   int64
 30  Profession_Software Engineer       2556 non-null   int64
 31  Profession_Student                 2556 non-null   int64
 32  Profession_Teacher                 2556 non-null   int64
 33  Profession_Travel Consultant       2556 non-null   int64
 34  Profession_UX/UI Designer          2556 non-null   int64
 35  Profession_Unknown                 2556 non-null   int64
dtypes: int64(36)
memory usage: 719.0 KB

In [39]:
profession_encoded.head()

,Profession_Accountant,Profession_Architect,Profession_Business Analyst,Profession_Chef,Profession_Chemist,Profession_Civil Engineer,Profession_Consultant,Profession_Content Writer,Profession_Customer Support,Profession_Data Scientist,...,Profession_Plumber,Profession_Research Analyst,Profession_Researcher,Profession_Sales Executive,Profession_Software Engineer,Profession_Student,Profession_Teacher,Profession_Travel Consultant,Profession_UX/UI Designer,Profession_Unknown
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [40]:
print(df["Degree"].dtype)
print(df["Degree"].nunique())
print(df["Degree"].isnull().sum())
print(df["Degree"].unique())

str
27
0
<StringArray>
[      'MA',    'B.Com',    'M.Com',       'MD',       'BE',      'MCA',
       'BA',      'LLM',      'BCA', 'Class 12',     'B.Ed',   'M.Tech',
      'LLB',   'B.Arch',       'ME',      'MBA',  'M.Pharm',     'MBBS',
      'PhD',      'BSc',      'MSc',      'MHM',      'BBA',      'BHM',
   'B.Tech',     'M.Ed',  'B.Pharm']
Length: 27, dtype: str

In [41]:
degree_encoded = pd.get_dummies(
    df["Degree"],
    prefix="Degree",
    dtype=int
)

In [42]:
degree_encoded.info()
degree_encoded.head()

<class 'pandas.DataFrame'>
RangeIndex: 2556 entries, 0 to 2555
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Degree_B.Arch    2556 non-null   int64
 1   Degree_B.Com     2556 non-null   int64
 2   Degree_B.Ed      2556 non-null   int64
 3   Degree_B.Pharm   2556 non-null   int64
 4   Degree_B.Tech    2556 non-null   int64
 5   Degree_BA        2556 non-null   int64
 6   Degree_BBA       2556 non-null   int64
 7   Degree_BCA       2556 non-null   int64
 8   Degree_BE        2556 non-null   int64
 9   Degree_BHM       2556 non-null   int64
 10  Degree_BSc       2556 non-null   int64
 11  Degree_Class 12  2556 non-null   int64
 12  Degree_LLB       2556 non-null   int64
 13  Degree_LLM       2556 non-null   int64
 14  Degree_M.Com     2556 non-null   int64
 15  Degree_M.Ed      2556 non-null   int64
 16  Degree_M.Pharm   2556 non-null   int64
 17  Degree_M.Tech    2556 non-null   int64
 18  Degree_MA        2556 non-null   int64
 19  Degree_MBA       2556 non-null   int64
 20  Degree_MBBS      2556 non-null   int64
 21  Degree_MCA       2556 non-null   int64
 22  Degree_MD        2556 non-null   int64
 23  Degree_ME        2556 non-null   int64
 24  Degree_MHM       2556 non-null   int64
 25  Degree_MSc       2556 non-null   int64
 26  Degree_PhD       2556 non-null   int64
dtypes: int64(27)
memory usage: 539.3 KB

,Degree_B.Arch,Degree_B.Com,Degree_B.Ed,Degree_B.Pharm,Degree_B.Tech,Degree_BA,Degree_BBA,Degree_BCA,Degree_BE,Degree_BHM,...,Degree_M.Tech,Degree_MA,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_PhD
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [43]:
df = pd.concat([df, degree_encoded], axis=1)

In [44]:
df.drop(columns=["Degree"], inplace=True)

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2556 entries, 0 to 2555
Columns: 108 entries, Gender to Degree_PhD
dtypes: float64(5), int64(102), str(1)
memory usage: 2.1 MB

In [46]:
df.head()

,Gender,Age,Working Professional or Student,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,...,Degree_M.Tech,Degree_MA,Degree_MBA,Degree_MBBS,Degree_MCA,Degree_MD,Degree_ME,Degree_MHM,Degree_MSc,Degree_PhD
0,0,37,1,NaN,2.0,NaN,NaN,4.0,2,1,...,0,1,0,0,0,0,0,0,0,0
1,1,60,1,NaN,4.0,NaN,NaN,3.0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0,42,1,NaN,2.0,NaN,NaN,3.0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,0,44,1,NaN,3.0,NaN,NaN,5.0,2,2,...,0,0,0,0,0,1,0,0,0,0
4,1,48,1,NaN,4.0,NaN,NaN,3.0,2,1,...,0,0,0,0,0,0,0,0,0,0

# Missing Value Handling

In [47]:
missing_values = df.isnull().sum()

missing_values = missing_values[missing_values > 0]

missing_values.sort_values(ascending=False)

Academic Pressure     2054
CGPA                  2054
Study Satisfaction    2054
Work Pressure          502
Job Satisfaction       502
dtype: int64

In [48]:
pd.crosstab(
    df["Working Professional or Student"],
    df["Academic Pressure"].isnull()
)

Academic Pressure                False  True
Working Professional or Student
0                                  502      0
1                                    0   2054

In [49]:
df["Academic Pressure"].value_counts(dropna=False).sort_index()

Academic Pressure
1.0      99
2.0      88
3.0     125
4.0      92
5.0      98
NaN    2054
Name: count, dtype: int64

The missing values in the following columns are logical (structural) missing values rather than data collection errors.

Student-related features:
- Academic Pressure
- CGPA
- Study Satisfaction

These are missing for working professionals because they are not applicable.

Working professional-related features:
- Work Pressure
- Job Satisfaction

These are missing for students because they are not applicable.

Since multiple machine learning models will be evaluated and several of them do not support NaN values, these logical missing values will be replaced with -1, which acts as a sentinel value representing "Not Applicable".

In [50]:
logical_missing_cols = [
    "Academic Pressure",
    "CGPA",
    "Study Satisfaction",
    "Work Pressure",
    "Job Satisfaction"
]

df[logical_missing_cols] = df[logical_missing_cols].fillna(-1)

In [51]:
df.isnull().sum()

Gender                             0
Age                                0
Working Professional or Student    0
Academic Pressure                  0
Work Pressure                      0
                                  ..
Degree_MD                          0
Degree_ME                          0
Degree_MHM                         0
Degree_MSc                         0
Degree_PhD                         0
Length: 108, dtype: int64

# Save Processed Dataset

In [52]:
df.to_csv(
    "../Dataset/Processed/MindSense_AI_Cleaned_Dataset_v1.csv",
    index=False
)